info:
  component: Discovery Server

#Default
spring:
  profiles: default
server:
  port: 8761
eureka:
  instance:
    hostname: default-eureka-server.com
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
#Peer 1
spring:
  profiles: peer1  
server:
  port: 8762
eureka:
  instance:
    hostname: peer1-server.com
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2-server.com:8763/eureka/, http://peer3-server.com:8764/eureka/

---
spring:
  profiles: peer2  
server:
  port: 8763  
eureka:
  instance:
    hostname: peer2-server.com
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1-server.com:8762/eureka/, http://peer3-server.com:8764/eureka/

---
#Peer 3    
spring:
  profiles: peer3  
server:
  port: 8764
eureka:
  instance:
    hostname: peer3-server.com
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1-server.com:8762/eureka/, http://peer2-server.com:8763/eureka/
