server:
  port: 8090  

zuul:
  routes:
    usuario:      
      service-id: co.ada.core.microservicio.usuario
      path: /api/crud/**
    security:
      service-id: co.ada.core.server.oauth
      path: /api/security/**
      sensitive-headers: Cookie,Set-Cookie
    prueba:
      service-id: co.ada.test.microservicio.prueba
      path: /api/prueba/**

Hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 20000
  
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://10.1.140.20:9411/
