info:
  component: Discovery Server

#Default
spring:
  profiles: Default
  
server:
  port: 8761
  waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync  

eureka:
  instance:    
    hostname: localhost
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka   

---    
#Peer 1
spring:
  profiles: peer1
  
server:
  port: 8762
  waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync    
  
eureka:
  instance:
    hostname: localhost
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:      
      defaultZone: http://localhost:8763/eureka, http://localhost:8764/eureka, http://localhost:8761/eureka
   
   
   
---
spring:
  profiles: peer2
  
server:
  port: 8763
  waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync    
  
eureka:
  instance:
    hostname: localhost
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:      
      defaultZone: http://localhost:8764/eureka, http://localhost:8761/eureka, http://localhost:8762/eureka

---    
#Peer 3    
spring:
  profiles: peer3
  
server:
  port: 8764
  waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync    
  
eureka:
  instance:
    hostname: localhost
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:      
      defaultZone: http://localhost:8763/eureka, http://localhost:8762/eureka, http://localhost:8761/eureka
