server:
  port: 8090  

eureka:
  client:
    serviceUrl:
      defaulZone: http://localhost:8761/eureka      

zuul:
  routes:
    usuario:      
      service-id: co.ada.core.microservicio.usuario
      path: /api/crud/**
    security:
      service-id: co.ada.core.server.oauth
      path: /api/security/**
      sensitive-headers: Cookie,Set-Cookie

Hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 20000
  
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/  
