server:
  port: ${PORT:0}  

eureka:
  client:
    serviceUrl:
      defaulZone: http://localhost:8761/eureka 
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}      

Hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
  
spring:
  datasource:
    url: jdbc:oracle:thin:@//10.1.140.101:1521/db102
    username: USER_ADM
    password: USER_ADM
    driver-class-name: oracle.jdbc.driver.OracleDriver

    jpa:
      database-platform: org.hibernate.dialect.Oracle11gDialect
      hibernate.ddl-auto: none

logging:
  pattern:
    console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  level:
    org:
      hibernate.SQL: debug
