server:
  port: 8090
  
info:
  component: Gateway Server

zuul:
  routes:
    core-server-security:
      service-id: co.ada.core.server.security
      path: /api/security/**
      sensitive-headers: Cookie,Set-Cookie    
    core-service-usuario:      
      service-id: co.ada.core.microservicio.usuario
      path: /api/core/usuarios/**    
    core-service-userlogin:      
      service-id: co.ada.core.service.userlogin
      path: /api/core/userlogin/**    
    core-service-utility:
      service-id: co.ada.core.service.utility
      path: /api/core/utility/** 
    contabilidad-tercero:
      service-id: co.ada.sicof.contabilidad.tercero
      path: /api/contabilidad/tercero/**
    nomina-novedaddescuento:
      service-id: co.ada.sicof.nomina.novedaddescuento
      path: /api/nomina/novedaddescuento/**  
    nomina-paises:
      service-id: co.ada.sicof.nomina.paises
      path: /api/nomina/paises/**	
    nomina-departamentos:
      service-id: co.ada.sicof.nomina.departamentos
      path: /api/nomina/departamentos/**	  
    nomina-tipoempleado:
      service-id: co.ada.sicof.nomina.tipoempleado
      path: /api/nomina/tipoempleado/**   
    nomina-estadosnovedad:
      service-id: co.ada.sicof.nomina.estadosnovedad
      path: /api/nomina/estadosnovedad/**    
    nomina-jefeempleados:
      service-id: co.ada.sicof.nomina.jefeempleados
      path: /api/nomina/jefeempleados/**
    nomina-periodosliquidacion:
      service-id: co.ada.sicof.nomina.periodosliquidacion
      path: /api/nomina/periodosliquidacion/**
    nomina-tiposliquidacion:
      service-id: co.ada.sicof.nomina.tiposliquidacion
      path: /api/nomina/tiposliquidacion/**
    nomina-juzgados:
      service-id: co.ada.sicof.nomina.juzgados
      path: /api/nomina/juzgados/**
    nomina-novedadconcepto:
      service-id: co.ada.sicof.nomina.novedadconcepto
      path: /api/nomina/novedadconcepto/**
    nomina-empleados:
      service-id: co.ada.sicof.nomina.empleados
      path: /api/nomina/empleados/**
    nomina-conceptos:
      service-id: co.ada.sicof.nomina.conceptos
      path: /api/nomina/conceptos/**
    nomina-tiposnomina:
      service-id: co.ada.sicof.nomina.tiposnomina
      path: /api/nomina/tiposnomina/**
    nomina-tiposenfermedad:
      service-id: co.ada.sicof.nomina.tiposenfermedad
      path: /api/nomina/tiposenfermedad/**
    nomina-tiposvalorembargo:
      service-id: co.ada.sicof.nomina.tiposvalorembargo
      path: /api/nomina/tiposvalorembargo/**
    nomina-ciudades:
      service-id: co.ada.sicof.nomina.ciudades
      path: /api/nomina/ciudades/**
    test-pruebamodel:
      service-id: co.ada.test.microservicio.pruebamodel
      path: /api/prueba/**
    rentas-recaudo:
      service-id: co.ada.sicof.rentas.recaudo
      path: /api/rentas/recaudo/**
    rentas-recargo:
      service-id: co.ada.sicof.rentas.recargo
      path: /api/rentas/recargo/**
    rentas-liquidacion-novedadobjeto:
      service-id: co.ada.sicof.rentas.liquidacion.novedadobjeto
      path: /api/rentas/novedadobjeto/**
    rentas-recaudo-formapago:
      service-id: co.ada.sicof.rentas.recaudo.formapago
      path: /api/rentas/formapago/**
    rentas-facturacionperiodo:
      service-id: co.ada.sicof.rentas.facturacionperiodo
      path: /api/rentas/facturacionperiodo/**
    rentas-tipoliquidacion:
      service-id: co.ada.sicof.rentas.tipoliquidacion
      path: /api/rentas/tipoliquidacion/**
    rentas-fuenteingreso:
      service-id: co.ada.sicof.rentas.fuenteingreso
      path: /api/rentas/fuenteingreso/**
    rentas-concepto:
      service-id: co.ada.sicof.rentas.concepto
      path: /api/rentas/concepto/**
    rentas-tiposconcepto:
      service-id: co.ada.sicof.rentas.tiposconcepto
      path: /api/rentas/tiposconcepto/**  
    rentas-tipofacturacion:
      service-id: co.ada.sicof.rentas.tipofacturacion
      path: /api/rentas/tipofacturacion/**	   
    presupuesto-maeconceptoscuentacobrar:
      service-id: co.ada.sicof.presupuesto.maeconceptoscuentacobrar
      path: /api/presupuesto/maeconceptoscuentacobrar/**  
      
Hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 20000
  
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://10.1.140.20:9411/
